# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 02:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sample_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('entrez_gene_id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('chromosome', models.CharField(max_length=8, null=True)),
                ('gene_type', models.CharField(max_length=16)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=None)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), null=True, size=None)),
            ],
            options={
                'db_table': 'cognoma_genes',
            },
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='status',
        ),
        migrations.AddField(
            model_name='classifier',
            name='genes',
            field=models.ManyToManyField(to='api.Gene'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='api.Gene'),
        ),
    ]
