# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-05 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_genes_mutations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='task_id',
            field=models.IntegerField(null=True),
        )
    ]
