# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-05 19:19
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_id_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='notebook_file',
            field=models.FileField(null=True, upload_to=api.models.Classifier.classifier_notebook_file_path),
        ),
    ]
