# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-11 20:46
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_classifier_notebook_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='results',
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='task_id',
        ),
        migrations.AddField(
            model_name='classifier',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classifier',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='description',
            field=models.CharField(max_length=2048, null=True, verbose_name='optional description'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='locked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='max_attempts',
            field=models.IntegerField(default=1, verbose_name='max number of times this job can attempt to run'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='optional name'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3),
        ),
        migrations.AddField(
            model_name='classifier',
            name='run_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 11, 20, 46, 53, 396054, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classifier',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('failed_retrying', 'Failed - Retrying'), ('dequeued', 'Dequeued'), ('failed', 'Failed'), ('completed', 'Completed')], default='queued', max_length=17),
        ),
        migrations.AddField(
            model_name='classifier',
            name='timeout',
            field=models.IntegerField(default=600, verbose_name='timeout in seconds'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='type',
            field=models.CharField(default='classifier-search', max_length=255, validators=[django.core.validators.RegexValidator(message='Classifier type can only contain lowercase alphanumeric characters, dashes, and underscores.', regex='^[a-z0-9\\-_]+$')]),
        ),
        migrations.AddField(
            model_name='classifier',
            name='worker_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
