# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-11 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170711_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifier',
            old_name='type',
            new_name='title',
        ),
    ]
