# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170711_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='run_at',
        ),
    ]
