# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_classifier_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='fail_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='fail_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
