# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_fail_message_and_reason_to_classifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='fail_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
