# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-11 18:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_increase_fail_message_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gene',
            name='description',
            field=models.TextField(),
        ),
    ]
